[config]
image_directory = 'img'
thumbnail_size = 400 # longest side will never exceede 400 pixels..
thumbnail_quality = 60 # jpg quality option
new_images_timeframe = 604800 # = 60*60*24*7 = one week in seconds (unix epoch time)

[about]
name = 'Emil Bratt'
image = '2026_02_02__22_18_47__78.jpg'
bio = """
Velkommen!

Jeg er en eksfotograf som startet for fullt i 2011 og sluttet under Covid.
Har vært med på mange spennende oppdrag gjennom min karriere.

Jeg fotograferer alt mulig. Da jeg drev proffesjonelt,
fotograferte jeg sport, konsert, event, bryllup, gravid, nyfødt og sist men ikke minst, natur.

Har veldig lyst å starte opp proffesjonelt igjen,
men først skal det taes bilder rekreasjonelt. :)
Bildene du finner her er tilgjengelige for nedlasting og helt gratis for deg som privatperson.
Det vil komme flere bilder etter hvert.

Tidligere delte jeg alt sammen på facebook og instagram, men det gjør jeg ikke lenger.
Sosiale medier har desverre blitt vanskeligere å bruke for personer uten brukerkonto,
så jeg tok hammern fatt og snekra sammen denne nettsida.
Er du kanskje en utvikler selv og lurer på hva som holder denne nettsida sammen? Her ligger
<button><a href="https://github.com/emilbratt/frifoto.emilbratt.no/">kildekode!</a></button>
"""

[images]
'2020_08_15__18_00_29__38.jpg' = { tags = [ 'Natur', 'Sommer' ] }
'2023_02_02__15_42_51__74.jpg' = { tags = [ 'Natur', 'Skumring', 'Vinter' ] }
'2024_05_20__19_51_15__09.jpg' = { tags = [ 'Natur', ] }
'2024_10_14__13_28_15__68.jpg' = { tags = [ 'Høst', 'Natur', ] }
'2025_05_26__17_44_37__86.jpg' = { tags = [ 'Allvi', ] }
'2025_05_26__17_44_51__25.jpg' = { tags = [ 'Allvi', ] }
'2025_05_26__17_45_25__57.jpg' = { tags = [ 'Allvi', ] }
'2024_05_30__21_31_13__10.jpg' = { tags = [ 'Natur', 'Vann', ] }
'2024_05_30__21_37_10__46.jpg' = { tags = [ 'Natur', 'Vann', ] }
'2024_05_30__21_39_00__33.jpg' = { tags = [ 'Natur', 'Vann', ] }
'2025_10_28__13_57_15__56.jpg' = { rating = 3, tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_23__14_31_27__44.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_23__14_39_57__13.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__14_46_23__77.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__14_55_24__12.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__14_58_44__79.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__15_07_05__43.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__15_17_47__46.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_23__15_26_43__11.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_07_09__1.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_28__14_19_24__99.jpg' = { tags = [ 'Fugler', 'Lade Hundepark', ] }
'2025_10_28__14_22_47__12.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_28__14_23_30__11.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_28__14_33_04__63.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_33_45__91.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_34_12__56.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_34_30__8.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_37_30__55.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_39_04__72.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_41_14__09.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_42_18__53.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_45_04__66.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_28__14_48_47__99.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_13_27__55.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_14_09__15.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_14_47__73.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_14_53__63.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_14_55__28.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_14_55__9.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_17_23__98.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_17_26__32.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_19_25__73.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_20_28__34.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_20_35__57.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_21_03__82.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_27_48__74.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_27_54__27.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_31_48__07.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_34_02__16.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_35_18__2.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_37_02__56.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_42_48__77.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_29__13_45_27__39.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_45_27__75.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_45_28__56.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_47_10__72.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_47_55__89.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_10_29__13_49_28__92.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__13_56_37__2.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_03_42__67.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_06_06__07.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_06_22__96.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_07_58__19.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_08_51__62.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_17_35__29.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_25_18__43.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_26_33__01.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_26_35__85.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_29__14_34_56__33.jpg' = { tags = [ 'Høst', 'Natur', ] }
'2025_10_31__12_13_20__11.jpg' = { tags = [ 'Høst', 'Natur', ] }
'2025_10_31__12_14_12__27.jpg' = { tags = [ 'Høst', 'Natur', ] }
'2025_10_31__13_08_15__36.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_46_22__03.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_48_40__27.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_52_38__16.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_52_43__51.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_53_40__57.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_56_00__42.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__13_56_48__6.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_07_50__85.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_10_47__9.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_23_13__54.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_27_25__35.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_35_53__13.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_36_32__17.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_36_58__47.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_10_31__14_39_23__94.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_01__12_45_35__09.jpg' = { tags = [ 'Allvi', ] }
'2025_11_01__12_46_37__84.jpg' = { tags = [ 'Allvi', ] }
'2025_11_01__13_01_12__45.jpg' = { tags = [ 'Allvi', ] }
'2025_11_01__13_09_36__52.jpg' = { tags = [ 'Høst', 'Natur' ] }
'2025_11_02__13_12_00__68.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_15_18__72.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_15_49__5.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_16_01__35.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_16_01__86.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_19_05__75.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_19_08__45.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_19_13__97.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_19_45__05.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_24_03__63.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_24_25__54.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_25_05__9.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_26_14__88.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_31_15__06.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_34_36__6.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_34_46__77.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_36_00__58.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_46_45__79.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_54_04__11.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_54_54__27.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__13_59_56__24.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__14_00_55__63.jpg' = { tags = [ 'Allvi', 'Lade Hundepark', ] }
'2025_11_02__14_03_45__12.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__14_04_17__47.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_02__14_05_22__72.jpg' = { tags = [ 'Lade Hundepark', ] }
'2025_11_03__12_55_47__32.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__12_56_51__5.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__12_57_06__24.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_03_51__47.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_05_15__36.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_31_40__15.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_40_20__62.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_42_06__16.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_42_41__23.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_42_59__87.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_43_33__49.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_03__13_51_01__93.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_47_37__21.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_50_19__97.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_55_48__1.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_55_50__64.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_56_17__69.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_56_24__71.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_58_24__73.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_58_28__15.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_58_42__28.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__14_59_20__92.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__15_08_02__39.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__15_08_55__77.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2025_11_06__15_09_02__41.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_04__22_01_05__66.jpg' = { tags = [ 'Natur', 'Nordlys', 'Natt', ] }
'2026_01_02__22_24_03__74.jpg' = { tags = [ 'Natur', 'Nordlys', 'Natt', ] }
'2026_01_20__15_07_52__62.jpg' = { tags = [ 'Allvi', 'Nordbyen Hundepark', ] }
'2026_01_20__15_25_26__37.jpg' = { tags = [ 'Allvi', 'Nordbyen Hundepark', ] }
'2026_01_24__15_37_01__28.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__15_44_05__88.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__15_44_14__14.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__15_47_08__20.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__15_51_02__05.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__15_52_40__43.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_24__16_03_30__01.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_01_25__22_49_52__88.jpg' = { tags = [ 'Allvi', 'Natt', ] }
'2026_01_27__23_09_39__41.jpg' = { tags = [ 'Arkitektur', 'Natt', ] }
'2026_02_01__20_15_26__45.jpg' = { tags = [ 'Allvi', 'Natt', ] }
'2026_02_02__21_46_33__38.jpg' = { tags = [ 'Allvi', 'Natt', ] }
'2026_02_02__22_18_47__78.jpg' = { tags = [ 'Allvi', 'Natt', 'Portrett' ] }
'2026_02_02__22_30_51__54.jpg' = { tags = [ 'Allvi', 'Natt', ] }
'2026_02_11__10_51_31__58.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_03_58__04.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_13_40__02.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_22_53__75.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_23_12__99.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_31_05__08.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_32_44__39.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_34_19__66.jpg' = { tags = [ 'Allvi', 'Nordbyen Hundepark', ] }
'2026_02_11__11_43_44__38.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_43_45__27.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
'2026_02_11__11_49_37__46.jpg' = { tags = [ 'Nordbyen Hundepark', ] }
